spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: none #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        # show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace